name: core
description: "Provide core functionality for the app"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  dependencies:
    path: ../dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
